title: Lsong’s Notes
description: Lsong’s Notes
theme: just-the-docs

url: https://notes.lsong.org

aux_links:
  home: https://lsong.org
  blog: https://blog.lsong.org
  books: https://lsong.org/books
  music: https://lsong.org/music
  apps: https://lsong.org/apps.html